sensors:  
  - point_cloud_camera

point_cloud_camera:
    sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /points_world
    max_range: 2.0
    point_subsample: 1    # 点群の間引き率
    padding_offset: 0.005   # ロボットモデルの膨張オフセット [m]
    padding_scale: 1.0    # ロボットモデルのスケーリング係数
    max_update_rate: 1.0  # OctoMap更新の最大周波数 [Hz]
    filtered_cloud_topic: filtered_cloud # フィルタ後の点群をパブリッシュするトピック名